In [3]:
import numpy as np

In [8]:
A = np.arange(2)
A

array([0, 1])

In [10]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [15]:
X = np.array(my_list)
X

array([1, 2, 3])

In [18]:
matrice = [[1,2,3], [4,5,6], [7,8,9]]
matrice

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
Y = np.array(matrice)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
E = np.arange(0,11,2)
E

array([ 0,  2,  4,  6,  8, 10])

In [26]:
zero_ones = np.zeros(3)
zero_ones

array([0., 0., 0.])

In [29]:
B = np.zeros((5,5))
B

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
B1 = np.ones(3)
B1

array([1., 1., 1.])

In [45]:
# linspace
# création du vecteur
a1 = np.linspace(0,10,3)
a2 = np.linspace(0, 5, 20)
a3 = np.linspace(0,5)
a3

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [44]:
# matrice identité
M1 = np.eye(3)
M1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
# création de tableau aléatoire
# utilisation de random

# rand (création de forme de donnée, distribution uniforme)
a4 = np.random.rand(2)
a4

array([0.80402499, 0.02018169])

In [50]:
a5 = np.random.rand(2,2)
a5

array([[0.81635592, 0.91614195],
       [0.18710576, 0.64653812]])

In [52]:
a6 = np.random.randn(2)
a6


array([ 0.10758161, -1.02943363])

In [55]:
a7 = np.random.randn(5,5)
a7

array([[-0.11991803,  0.32885756,  0.47232008,  0.17455569,  1.83165973],
       [-0.41212249,  0.16368491, -0.55297432,  0.46068226,  0.30844364],
       [ 0.97446728, -1.28530471,  1.10256351,  0.86327363,  0.87597018],
       [ 0.24569654, -0.74570536,  1.40580708,  1.09028587,  0.40247832],
       [ 1.09772566, -0.32298834,  1.32645766, -1.02438897,  2.10827661]])

In [64]:
a8 = np.random.randint(1,100,50)
a9 = a8[a8 < 50]
a9

array([30, 15, 16, 38, 43, 16, 21, 15, 37, 10, 36, 45, 10, 41,  8, 33, 35,
        9,  7, 21, 13, 24, 27, 41,  8, 20, 45, 44, 21])